apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  labels:
    app: api-nodejs
spec:
  selector:
    app: api-nodejs
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  type: NodePort
