apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-nodejs
  name: api-nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-nodejs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 # vai criar 2 pods a mais ao atualizar
      maxUnavailable: 2 # vai atualizar de 2 em 2
  template:
    metadata:
      labels:
        app: api-nodejs
    spec:
      containers:
      - image: matheusgomesa/api_nestjs_typeorm:1.0
        name: node-api
        env:
          - name: DB_HOST
            value: postgres-clusterip
        resources:
          limits:
            cpu: 0.9 # capacidade maxima de 90% da cpu
            memory: 250Mi # capacidade maxima de 250Mb de memoria ram
          requests:
            cpu: 0.3
            memory: 150Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30 # ira verificar a cada 30s
          timeoutSeconds: 5
          failureThreshold: 3


