apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: api-express-deployment
  name: api-express-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api-express-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: api-express-deployment
    spec:
      containers:
      - image: matheusgomesa/api_express:5.0
        name: api-express
        resources:
          limits:
            cpu: 1
            memory: 128Mi
          requests:
            cpu: 0.5
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe: 
          exec:
            command: 
            - curl
            - -f
            - http://localhost:3000/
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
