apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: nginx-pvc
  name: nginx-pvc
  namespace: borabill
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: storage-class-nginx
  selector:
    matchLabels:
      storage: cluster-node-disk
