apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    storage: cluster-node-disk
  namespace: borabill
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/borabill
  storageClassName: storage-class-nginx
