apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  labels:
    app: nginx
    env: dev
spec:
  selector:
    app: nginx # configura quais pods o serviço deve bater
  ports:
  - port: 80 # porta do service
    name: http
    targetPort: 80 # porta do container/pod
  type: LoadBalancer
