apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 10
  selector:
    matchLabels: 
      app: nginx-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # pode ter até um pod a mais que o definido | pode ser usado porcetagem tbm ex: 10%
      maxUnavailable: 2 # vai atualizar de 2 em 2 | poderia usar 25% tbm
  template:
    metadata:
      labels: 
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.16.0
        name: nginx
        resources:
          limits:
            cpu: 0.5
            memory: 256Mi
          requests:
            cpu: 0.3
            memory: 64Mi


